# Generated by Django 3.2.4 on 2021-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlinject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
