# Generated by Django 3.2.4 on 2021-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlinject', '0002_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
